
USE ROLE ACCOUNTADMIN;

-- Compute: extra-small, auto-suspend fast so the trial credits last.
CREATE WAREHOUSE IF NOT EXISTS FOOD_DLV_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND   = 60
  AUTO_RESUME    = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Database + medallion schemas.
CREATE DATABASE IF NOT EXISTS FOOD_DLV;
CREATE SCHEMA  IF NOT EXISTS FOOD_DLV.RAW;       -- Bronze layer data (used to load the raw data)
CREATE SCHEMA  IF NOT EXISTS FOOD_DLV.STAGING;   -- Silver layer (used for staging data)
CREATE SCHEMA  IF NOT EXISTS FOOD_DLV.MARTS;     -- Gold layer (used to load final dim and fact and maret tables)

-- A role dbt/Airflow will use.
CREATE ROLE IF NOT EXISTS DBT_ROLE;
GRANT USAGE   ON WAREHOUSE FOOD_DLV_WH TO ROLE DBT_ROLE;
GRANT OPERATE ON WAREHOUSE FOOD_DLV_WH TO ROLE DBT_ROLE;
GRANT ALL     ON DATABASE  FOOD_DLV    TO ROLE DBT_ROLE;
GRANT ALL     ON ALL SCHEMAS IN DATABASE FOOD_DLV TO ROLE DBT_ROLE;
GRANT ALL     ON FUTURE SCHEMAS IN DATABASE FOOD_DLV TO ROLE DBT_ROLE;
GRANT ALL     ON FUTURE TABLES IN DATABASE FOOD_DLV TO ROLE DBT_ROLE;
GRANT ALL     ON FUTURE VIEWS  IN DATABASE FOOD_DLV TO ROLE DBT_ROLE;

-- Let your login use the role (replace with your Snowflake username).
SET my_user = CURRENT_USER();
GRANT ROLE DBT_ROLE TO USER IDENTIFIER($my_user);

SELECT 'setup complete' AS status;