USE ROLE ACCOUNTADMIN;
USE DATABASE FOOD_DLV;
USE SCHEMA RAW;
USE WAREHOUSE FOOD_DLV_WH;

-- Create the snowpipe for continues ingeestion
-- Loads the plain CSVs you uploaded to each raw/<table>/ folder. The header

CREATE OR REPLACE PIPE RAW.RESTAURANTS_PIPE AUTO_INGEST = TRUE AS COPY INTO RAW.restaurants FROM @FOOD_DLV_RAW_STAGE/restaurant/;
CREATE OR REPLACE PIPE RAW.USERS_PIPE AUTO_INGEST = TRUE AS COPY INTO RAW.users       FROM @FOOD_DLV_RAW_STAGE/users/;
CREATE OR REPLACE PIPE RAW.FOOD_PIPE AUTO_INGEST = TRUE AS COPY INTO RAW.food        FROM @FOOD_DLV_RAW_STAGE/food/;
CREATE OR REPLACE PIPE RAW.MENU_PIPE AUTO_INGEST = TRUE AS COPY INTO RAW.menu        FROM @FOOD_DLV_RAW_STAGE/menu/;
CREATE OR REPLACE PIPE RAW.ORDERS_PIPE AUTO_INGEST = TRUE AS COPY INTO RAW.orders      FROM @FOOD_DLV_RAW_STAGE/orders/;
CREATE OR REPLACE PIPE RAW.ORDER_ITEMS_PIPE AUTO_INGEST = TRUE AS COPY INTO RAW.order_items FROM @FOOD_DLV_RAW_STAGE/order_items/;
CREATE OR REPLACE PIPE RAW.REVIEWS_PIPE AUTO_INGEST = TRUE AS COPY INTO RAW.reviews     FROM @FOOD_DLV_RAW_STAGE/reviews/;

-- then wire the pipe's SQS ARN to an S3 bucket event notification.
SHOW PIPES;

SELECT SYSTEM$PIPE_STATUS('FOOD_PIPE');

--checks
SELECT 'restaurants' t, COUNT(*) n FROM RAW.restaurants --148541
UNION ALL SELECT 'users',       COUNT(*) FROM RAW.users
UNION ALL SELECT 'food',        COUNT(*) FROM RAW.food
UNION ALL SELECT 'menu',        COUNT(*) FROM RAW.menu
UNION ALL SELECT 'orders',      COUNT(*) FROM RAW.orders
UNION ALL SELECT 'order_items', COUNT(*) FROM RAW.order_items
UNION ALL SELECT 'reviews',     COUNT(*) FROM RAW.reviews
ORDER BY t;

--Notification Integration
CREATE OR REPLACE NOTIFICATION INTEGRATION FOOD_DLV_EMAIL_INT
enabled=true
Type=QUEUE
NOTIFICATION_PROVIDER=AWS_SNS
DIRECTION=OUTBOUND
AWS_SNS_TOPIC_ARN='<SNS_TOPIC_ARN>'
AWS_SNS_ROLE_ARN='<IAM_ROLE_ARN>';

GRANT USAGE ON INTEGRATION FOOD_DLV_EMAIL_INT TO ROLE DBT_ROLE;

-- Run this, then copy the one values into the IAM role trust policy.
DESC INTEGRATION FOOD_DLV_EMAIL_INT;
-- SF_AWS_IAM_USER_ARN  ->  the "AWS": principal in the trust policy(It will be same as the storage integration value, so no need to update this in IAM role)
-- SF_AWS_EXTERNAL_ID   ->  the sts:ExternalId condition

ALTER PIPE RESTAURANTS_PIPE
SET ERROR_INTEGRATION = 'FOOD_DLV_EMAIL_INT';

